replicaCount: 3
image:
  tag: "1.22.0"
environment: "production"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: nginx-prod.example.com
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 256Mi