apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-wait-svc
  labels:
    app: nginx-wait-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-wait-svc
  template:
    metadata:
      labels:
        app: nginx-wait-svc
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Ожидаю появления сервиса nginx-wait-svc-service..."
              until nslookup nginx-wait-svc-service.default.svc.cluster.local.; do
                echo "Сервис пока недоступен, повтор через 5 секунд..."
                sleep 5
              done
              echo "Сервис найден, можно запускать nginx"
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80